// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxoJ51ttxswj0X-89PVAN0UhR7K_zXJ7k',
    appId: '1:590503331505:android:af419d6c19be007660c490',
    messagingSenderId: '590503331505',
    projectId: 'tasklendar-dddfa',
    storageBucket: 'tasklendar-dddfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfV7aDaf06tLuf00-_CGwje7ugMC21KlE',
    appId: '1:590503331505:ios:4938cfab1446aca860c490',
    messagingSenderId: '590503331505',
    projectId: 'tasklendar-dddfa',
    storageBucket: 'tasklendar-dddfa.appspot.com',
    androidClientId: '590503331505-3tn4ecsksps48c0rmg8h240v8inb41lt.apps.googleusercontent.com',
    iosClientId: '590503331505-aj5b8ptmtmgfj8uecb2ga46dhofogncn.apps.googleusercontent.com',
    iosBundleId: 'tasklendar.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfV7aDaf06tLuf00-_CGwje7ugMC21KlE',
    appId: '1:590503331505:ios:33a26d69b960a0b560c490',
    messagingSenderId: '590503331505',
    projectId: 'tasklendar-dddfa',
    storageBucket: 'tasklendar-dddfa.appspot.com',
    androidClientId: '590503331505-3tn4ecsksps48c0rmg8h240v8inb41lt.apps.googleusercontent.com',
    iosClientId: '590503331505-5hasm6tmvi3r1fdp449a65uiqr6tjgh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklendar.RunnerTests',
  );
}
